# Generated by Django 3.2 on 2021-04-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0003_alter_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('grade', models.ManyToManyField(related_name='grade_course', to='school.Grade')),
                ('teachers', models.ManyToManyField(related_name='course', to='school.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('status', models.BooleanField(choices=[(True, 'active'), (False, 'inactive')], default=True)),
                ('grade', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.grade')),
                ('students', models.ManyToManyField(to='student.Student')),
            ],
        ),
    ]
